# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'OrganoSegmenterGui_V1 (1)BkVvpz.ui'
##
## Created by: Qt User Interface Compiler version 6.5.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGroupBox, QHBoxLayout, QHeaderView, QLabel,
    QLayout, QLineEdit, QListWidget, QListWidgetItem,
    QMainWindow, QPushButton, QRadioButton, QSizePolicy,
    QSlider, QSpacerItem, QTabWidget, QTableWidget,
    QTableWidgetItem, QTextBrowser, QToolBox, QVBoxLayout,
    QWidget)
import resources_rc

class Ui_OrganoSegmenterWindow(object):
    def setupUi(self, OrganoSegmenterWindow):
        if not OrganoSegmenterWindow.objectName():
            OrganoSegmenterWindow.setObjectName(u"OrganoSegmenterWindow")
        OrganoSegmenterWindow.resize(1078, 797)
        icon = QIcon()
        icon.addFile(u"OSlogo.ico", QSize(), QIcon.Normal, QIcon.Off)
        OrganoSegmenterWindow.setWindowIcon(icon)
        OrganoSegmenterWindow.setStyleSheet(u"")
        OrganoSegmenterWindow.setTabShape(QTabWidget.Rounded)
        self.centralwidget = QWidget(OrganoSegmenterWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout_2 = QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.LeftSideWidget = QWidget(self.centralwidget)
        self.LeftSideWidget.setObjectName(u"LeftSideWidget")
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LeftSideWidget.sizePolicy().hasHeightForWidth())
        self.LeftSideWidget.setSizePolicy(sizePolicy)
        self.LeftSideWidget.setMinimumSize(QSize(341, 771))
        icon1 = QIcon()
        icon1.addFile(u":/logos/logos/folder.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.FileManagementToolBox = QToolBox(self.LeftSideWidget)
        self.FileManagementToolBox.setObjectName(u"FileManagementToolBox")
        self.FileManagementToolBox.setGeometry(QRect(5, 4, 331, 201))
        self.FileManagementPage = QWidget()
        self.FileManagementPage.setObjectName(u"FileManagementPage")
        self.FileManagementPage.setGeometry(QRect(0, 0, 331, 171))
        self.BrowseFolderButton = QPushButton(self.FileManagementPage)
        self.BrowseFolderButton.setObjectName(u"BrowseFolderButton")
        self.BrowseFolderButton.setGeometry(QRect(268, 2, 61, 24))
        self.ImageFolder = QTextBrowser(self.FileManagementPage)
        self.ImageFolder.setObjectName(u"ImageFolder")
        self.ImageFolder.setGeometry(QRect(80, 0, 181, 26))
        self.ImageFolderLabel = QLabel(self.FileManagementPage)
        self.ImageFolderLabel.setObjectName(u"ImageFolderLabel")
        self.ImageFolderLabel.setGeometry(QRect(0, 2, 81, 16))
        self.DeltaXLabel = QLabel(self.FileManagementPage)
        self.DeltaXLabel.setObjectName(u"DeltaXLabel")
        self.DeltaXLabel.setGeometry(QRect(111, 150, 16, 16))
        self.DeltaZLabel = QLabel(self.FileManagementPage)
        self.DeltaZLabel.setObjectName(u"DeltaZLabel")
        self.DeltaZLabel.setGeometry(QRect(267, 150, 16, 16))
        self.DeltaYLabel = QLabel(self.FileManagementPage)
        self.DeltaYLabel.setObjectName(u"DeltaYLabel")
        self.DeltaYLabel.setGeometry(QRect(189, 150, 16, 16))
        self.DeltaYLineEdit = QLineEdit(self.FileManagementPage)
        self.DeltaYLineEdit.setObjectName(u"DeltaYLineEdit")
        self.DeltaYLineEdit.setGeometry(QRect(208, 147, 41, 21))
        self.DeltaXLineEdit = QLineEdit(self.FileManagementPage)
        self.DeltaXLineEdit.setObjectName(u"DeltaXLineEdit")
        self.DeltaXLineEdit.setGeometry(QRect(130, 147, 41, 21))
        self.VoxelSizeLabel = QLabel(self.FileManagementPage)
        self.VoxelSizeLabel.setObjectName(u"VoxelSizeLabel")
        self.VoxelSizeLabel.setGeometry(QRect(10, 150, 91, 16))
        self.DeltaZLineEdit = QLineEdit(self.FileManagementPage)
        self.DeltaZLineEdit.setObjectName(u"DeltaZLineEdit")
        self.DeltaZLineEdit.setGeometry(QRect(286, 147, 41, 21))
        self.FileListWidget = QListWidget(self.FileManagementPage)
        self.FileListWidget.setObjectName(u"FileListWidget")
        self.FileListWidget.setGeometry(QRect(0, 32, 328, 111))
        self.FileManagementToolBox.addItem(self.FileManagementPage, icon1, u"File Management")
        self.ExportToolBox = QToolBox(self.LeftSideWidget)
        self.ExportToolBox.setObjectName(u"ExportToolBox")
        self.ExportToolBox.setGeometry(QRect(5, 650, 331, 71))
        self.ExportPage = QWidget()
        self.ExportPage.setObjectName(u"ExportPage")
        self.ExportPage.setGeometry(QRect(0, 0, 331, 41))
        self.ExportMasksCheckBox = QCheckBox(self.ExportPage)
        self.ExportMasksCheckBox.setObjectName(u"ExportMasksCheckBox")
        self.ExportMasksCheckBox.setEnabled(False)
        self.ExportMasksCheckBox.setGeometry(QRect(10, 0, 71, 20))
        self.ExportMasksCheckBox.setChecked(True)
        self.ExportOverlaysCheckBox = QCheckBox(self.ExportPage)
        self.ExportOverlaysCheckBox.setObjectName(u"ExportOverlaysCheckBox")
        self.ExportOverlaysCheckBox.setGeometry(QRect(110, 0, 81, 20))
        self.ExportOverlaysCheckBox.setChecked(True)
        self.ExportCompositeCheckBox = QCheckBox(self.ExportPage)
        self.ExportCompositeCheckBox.setObjectName(u"ExportCompositeCheckBox")
        self.ExportCompositeCheckBox.setGeometry(QRect(230, 0, 81, 20))
        self.ExportCompositeCheckBox.setChecked(True)
        self.ExportCSVCheckBox = QCheckBox(self.ExportPage)
        self.ExportCSVCheckBox.setObjectName(u"ExportCSVCheckBox")
        self.ExportCSVCheckBox.setEnabled(False)
        self.ExportCSVCheckBox.setGeometry(QRect(230, 20, 61, 20))
        self.ExportCSVCheckBox.setChecked(True)
        self.ExportChannelsCheckBox = QCheckBox(self.ExportPage)
        self.ExportChannelsCheckBox.setObjectName(u"ExportChannelsCheckBox")
        self.ExportChannelsCheckBox.setGeometry(QRect(10, 20, 81, 20))
        self.ExportChannelsCheckBox.setChecked(False)
        self.ExportParametersCheckBox = QCheckBox(self.ExportPage)
        self.ExportParametersCheckBox.setObjectName(u"ExportParametersCheckBox")
        self.ExportParametersCheckBox.setGeometry(QRect(110, 20, 81, 20))
        self.ExportParametersCheckBox.setChecked(True)
        icon2 = QIcon()
        icon2.addFile(u":/logos/logos/export.png", QSize(), QIcon.Normal, QIcon.Off)
        self.ExportToolBox.addItem(self.ExportPage, icon2, u"Export")
        self.SettingsToolBox = QToolBox(self.LeftSideWidget)
        self.SettingsToolBox.setObjectName(u"SettingsToolBox")
        self.SettingsToolBox.setEnabled(True)
        self.SettingsToolBox.setGeometry(QRect(5, 210, 331, 431))
        self.ChannelsPreprocessingPage = QWidget()
        self.ChannelsPreprocessingPage.setObjectName(u"ChannelsPreprocessingPage")
        self.ChannelsPreprocessingPage.setGeometry(QRect(0, 0, 331, 311))
        self.ChannelPreprocessingComboBox = QComboBox(self.ChannelsPreprocessingPage)
        self.ChannelPreprocessingComboBox.setObjectName(u"ChannelPreprocessingComboBox")
        self.ChannelPreprocessingComboBox.setGeometry(QRect(60, 10, 211, 22))
        self.AddPreprocessingButton = QPushButton(self.ChannelsPreprocessingPage)
        self.AddPreprocessingButton.setObjectName(u"AddPreprocessingButton")
        self.AddPreprocessingButton.setGeometry(QRect(278, 10, 51, 51))
        self.RemovePreprocessingButton = QPushButton(self.ChannelsPreprocessingPage)
        self.RemovePreprocessingButton.setObjectName(u"RemovePreprocessingButton")
        self.RemovePreprocessingButton.setGeometry(QRect(278, 146, 51, 51))
        self.ChannelPreprocessingLabel = QLabel(self.ChannelsPreprocessingPage)
        self.ChannelPreprocessingLabel.setObjectName(u"ChannelPreprocessingLabel")
        self.ChannelPreprocessingLabel.setGeometry(QRect(10, 10, 49, 16))
        self.MethodPreprocessingComboBox = QComboBox(self.ChannelsPreprocessingPage)
        self.MethodPreprocessingComboBox.addItem("")
        self.MethodPreprocessingComboBox.addItem("")
        self.MethodPreprocessingComboBox.addItem("")
        self.MethodPreprocessingComboBox.addItem("")
        self.MethodPreprocessingComboBox.setObjectName(u"MethodPreprocessingComboBox")
        self.MethodPreprocessingComboBox.setGeometry(QRect(60, 40, 211, 22))
        self.PreprocessingMethodLabel = QLabel(self.ChannelsPreprocessingPage)
        self.PreprocessingMethodLabel.setObjectName(u"PreprocessingMethodLabel")
        self.PreprocessingMethodLabel.setGeometry(QRect(10, 40, 49, 16))
        self.PreprocessingListWidget = QListWidget(self.ChannelsPreprocessingPage)
        self.PreprocessingListWidget.setObjectName(u"PreprocessingListWidget")
        self.PreprocessingListWidget.setGeometry(QRect(10, 104, 261, 121))
        self.Parameter1PreprocessingLabel = QLabel(self.ChannelsPreprocessingPage)
        self.Parameter1PreprocessingLabel.setObjectName(u"Parameter1PreprocessingLabel")
        self.Parameter1PreprocessingLabel.setEnabled(False)
        self.Parameter1PreprocessingLabel.setGeometry(QRect(10, 76, 41, 21))
        self.Parameter1PreprocessingLineEdit = QLineEdit(self.ChannelsPreprocessingPage)
        self.Parameter1PreprocessingLineEdit.setObjectName(u"Parameter1PreprocessingLineEdit")
        self.Parameter1PreprocessingLineEdit.setEnabled(False)
        self.Parameter1PreprocessingLineEdit.setGeometry(QRect(50, 76, 81, 21))
        self.Parameter1PreprocessingLineEdit.setInputMethodHints(Qt.ImhDigitsOnly)
        self.Parameter2PreprocessingLineEdit = QLineEdit(self.ChannelsPreprocessingPage)
        self.Parameter2PreprocessingLineEdit.setObjectName(u"Parameter2PreprocessingLineEdit")
        self.Parameter2PreprocessingLineEdit.setEnabled(False)
        self.Parameter2PreprocessingLineEdit.setGeometry(QRect(190, 76, 81, 21))
        self.Parameter2PreprocessingLabel = QLabel(self.ChannelsPreprocessingPage)
        self.Parameter2PreprocessingLabel.setObjectName(u"Parameter2PreprocessingLabel")
        self.Parameter2PreprocessingLabel.setEnabled(False)
        self.Parameter2PreprocessingLabel.setGeometry(QRect(140, 76, 51, 21))
        icon3 = QIcon()
        icon3.addFile(u":/logos/logos/processing.png", QSize(), QIcon.Normal, QIcon.Off)
        self.SettingsToolBox.addItem(self.ChannelsPreprocessingPage, icon3, u"Channels Preprocessing")
        self.NucleiSegmentationPage = QWidget()
        self.NucleiSegmentationPage.setObjectName(u"NucleiSegmentationPage")
        self.NucleiSegmentationPage.setEnabled(True)
        self.NucleiSegmentationPage.setGeometry(QRect(0, 0, 331, 311))
        self.NucleiSegmentationPage.setInputMethodHints(Qt.ImhNone)
        self.NmsSlider = QSlider(self.NucleiSegmentationPage)
        self.NmsSlider.setObjectName(u"NmsSlider")
        self.NmsSlider.setGeometry(QRect(100, 148, 201, 16))
        self.NmsSlider.setMaximum(10)
        self.NmsSlider.setPageStep(1)
        self.NmsSlider.setValue(3)
        self.NmsSlider.setOrientation(Qt.Horizontal)
        self.ProbSlider = QSlider(self.NucleiSegmentationPage)
        self.ProbSlider.setObjectName(u"ProbSlider")
        self.ProbSlider.setGeometry(QRect(100, 168, 201, 16))
        self.ProbSlider.setMaximum(10)
        self.ProbSlider.setPageStep(1)
        self.ProbSlider.setValue(3)
        self.ProbSlider.setOrientation(Qt.Horizontal)
        self.NmsThresholdLabel = QLabel(self.NucleiSegmentationPage)
        self.NmsThresholdLabel.setObjectName(u"NmsThresholdLabel")
        self.NmsThresholdLabel.setGeometry(QRect(10, 146, 81, 16))
        self.ProbThresholdLabel = QLabel(self.NucleiSegmentationPage)
        self.ProbThresholdLabel.setObjectName(u"ProbThresholdLabel")
        self.ProbThresholdLabel.setGeometry(QRect(10, 168, 81, 16))
        self.ChannelNucleiLabel = QLabel(self.NucleiSegmentationPage)
        self.ChannelNucleiLabel.setObjectName(u"ChannelNucleiLabel")
        self.ChannelNucleiLabel.setGeometry(QRect(140, 2, 49, 16))
        self.ChannelNucleiComboBox = QComboBox(self.NucleiSegmentationPage)
        self.ChannelNucleiComboBox.setObjectName(u"ChannelNucleiComboBox")
        self.ChannelNucleiComboBox.setGeometry(QRect(200, 0, 129, 22))
        self.VolumeLimitLabel = QLabel(self.NucleiSegmentationPage)
        self.VolumeLimitLabel.setObjectName(u"VolumeLimitLabel")
        self.VolumeLimitLabel.setGeometry(QRect(10, 194, 61, 22))
        self.VolumeMaxLabel = QLabel(self.NucleiSegmentationPage)
        self.VolumeMaxLabel.setObjectName(u"VolumeMaxLabel")
        self.VolumeMaxLabel.setGeometry(QRect(200, 194, 31, 22))
        self.VolumeMinLineEdit = QLineEdit(self.NucleiSegmentationPage)
        self.VolumeMinLineEdit.setObjectName(u"VolumeMinLineEdit")
        self.VolumeMinLineEdit.setGeometry(QRect(120, 194, 51, 22))
        self.VolumeMaxLineEdit = QLineEdit(self.NucleiSegmentationPage)
        self.VolumeMaxLineEdit.setObjectName(u"VolumeMaxLineEdit")
        self.VolumeMaxLineEdit.setGeometry(QRect(230, 194, 51, 22))
        self.ExploreVolumesWindowButton = QPushButton(self.NucleiSegmentationPage)
        self.ExploreVolumesWindowButton.setObjectName(u"ExploreVolumesWindowButton")
        self.ExploreVolumesWindowButton.setEnabled(False)
        self.ExploreVolumesWindowButton.setGeometry(QRect(10, 220, 161, 24))
        icon4 = QIcon()
        icon4.addFile(u":/logos/logos/search.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.ExploreVolumesWindowButton.setIcon(icon4)
        self.ChangeModelButton = QPushButton(self.NucleiSegmentationPage)
        self.ChangeModelButton.setObjectName(u"ChangeModelButton")
        self.ChangeModelButton.setGeometry(QRect(249, 29, 81, 26))
        self.ChangeModelTextBrowser = QTextBrowser(self.NucleiSegmentationPage)
        self.ChangeModelTextBrowser.setObjectName(u"ChangeModelTextBrowser")
        self.ChangeModelTextBrowser.setGeometry(QRect(127, 29, 121, 26))
        self.ChangeModelTextBrowser.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.DetectNucleiCheckBox = QCheckBox(self.NucleiSegmentationPage)
        self.DetectNucleiCheckBox.setObjectName(u"DetectNucleiCheckBox")
        self.DetectNucleiCheckBox.setEnabled(False)
        self.DetectNucleiCheckBox.setGeometry(QRect(10, 0, 111, 20))
        self.DetectNucleiCheckBox.setCheckable(True)
        self.DetectNucleiCheckBox.setChecked(True)
        self.ResampleByGroupBox = QGroupBox(self.NucleiSegmentationPage)
        self.ResampleByGroupBox.setObjectName(u"ResampleByGroupBox")
        self.ResampleByGroupBox.setGeometry(QRect(10, 58, 318, 81))
        self.ResampleXLineEdit = QLineEdit(self.ResampleByGroupBox)
        self.ResampleXLineEdit.setObjectName(u"ResampleXLineEdit")
        self.ResampleXLineEdit.setGeometry(QRect(30, 24, 60, 21))
        self.ResampleZLineEdit = QLineEdit(self.ResampleByGroupBox)
        self.ResampleZLineEdit.setObjectName(u"ResampleZLineEdit")
        self.ResampleZLineEdit.setGeometry(QRect(250, 24, 60, 21))
        self.ResampleYLabel = QLabel(self.ResampleByGroupBox)
        self.ResampleYLabel.setObjectName(u"ResampleYLabel")
        self.ResampleYLabel.setGeometry(QRect(120, 24, 16, 21))
        self.ResampleYLineEdit = QLineEdit(self.ResampleByGroupBox)
        self.ResampleYLineEdit.setObjectName(u"ResampleYLineEdit")
        self.ResampleYLineEdit.setGeometry(QRect(140, 24, 60, 21))
        self.ResampleXLabel = QLabel(self.ResampleByGroupBox)
        self.ResampleXLabel.setObjectName(u"ResampleXLabel")
        self.ResampleXLabel.setGeometry(QRect(10, 24, 16, 21))
        self.ResampleZLabel = QLabel(self.ResampleByGroupBox)
        self.ResampleZLabel.setObjectName(u"ResampleZLabel")
        self.ResampleZLabel.setGeometry(QRect(230, 24, 16, 21))
        self.AutoResizeWindowButton = QPushButton(self.ResampleByGroupBox)
        self.AutoResizeWindowButton.setObjectName(u"AutoResizeWindowButton")
        self.AutoResizeWindowButton.setGeometry(QRect(10, 50, 161, 24))
        icon5 = QIcon()
        icon5.addFile(u":/logos/logos/resize.png", QSize(), QIcon.Normal, QIcon.Off)
        self.AutoResizeWindowButton.setIcon(icon5)
        self.UnityMuLabel = QLabel(self.NucleiSegmentationPage)
        self.UnityMuLabel.setObjectName(u"UnityMuLabel")
        self.UnityMuLabel.setGeometry(QRect(293, 194, 35, 22))
        self.VolumeMinLabel = QLabel(self.NucleiSegmentationPage)
        self.VolumeMinLabel.setObjectName(u"VolumeMinLabel")
        self.VolumeMinLabel.setGeometry(QRect(90, 194, 31, 22))
        self.NmsValueLabel = QLabel(self.NucleiSegmentationPage)
        self.NmsValueLabel.setObjectName(u"NmsValueLabel")
        self.NmsValueLabel.setGeometry(QRect(310, 146, 21, 16))
        self.ProbValueLabel = QLabel(self.NucleiSegmentationPage)
        self.ProbValueLabel.setObjectName(u"ProbValueLabel")
        self.ProbValueLabel.setGeometry(QRect(310, 168, 21, 16))
        self.DefaultModelComboBox = QComboBox(self.NucleiSegmentationPage)
        self.DefaultModelComboBox.addItem("")
        self.DefaultModelComboBox.addItem("")
        self.DefaultModelComboBox.addItem("")
        self.DefaultModelComboBox.setObjectName(u"DefaultModelComboBox")
        self.DefaultModelComboBox.setGeometry(QRect(10, 29, 111, 26))
        icon6 = QIcon()
        icon6.addFile(u":/logos/logos/nuclei.png", QSize(), QIcon.Normal, QIcon.Off)
        self.SettingsToolBox.addItem(self.NucleiSegmentationPage, icon6, u"Nuclei Segmentation")
        self.OrganoidSegmentationPage = QWidget()
        self.OrganoidSegmentationPage.setObjectName(u"OrganoidSegmentationPage")
        self.OrganoidSegmentationPage.setGeometry(QRect(0, 0, 331, 311))
        self.DetectOrganoidCheckBox = QCheckBox(self.OrganoidSegmentationPage)
        self.DetectOrganoidCheckBox.setObjectName(u"DetectOrganoidCheckBox")
        self.DetectOrganoidCheckBox.setGeometry(QRect(10, 10, 121, 20))
        self.DetectOrganoidCheckBox.setChecked(False)
        self.MethodOrganoidComboBox = QComboBox(self.OrganoidSegmentationPage)
        self.MethodOrganoidComboBox.addItem("")
        self.MethodOrganoidComboBox.addItem("")
        self.MethodOrganoidComboBox.setObjectName(u"MethodOrganoidComboBox")
        self.MethodOrganoidComboBox.setGeometry(QRect(70, 74, 259, 22))
        self.MethodOrganoidLabel = QLabel(self.OrganoidSegmentationPage)
        self.MethodOrganoidLabel.setObjectName(u"MethodOrganoidLabel")
        self.MethodOrganoidLabel.setGeometry(QRect(10, 74, 49, 22))
        self.Parameter1OrganoidLabel = QLabel(self.OrganoidSegmentationPage)
        self.Parameter1OrganoidLabel.setObjectName(u"Parameter1OrganoidLabel")
        self.Parameter1OrganoidLabel.setEnabled(True)
        self.Parameter1OrganoidLabel.setGeometry(QRect(10, 110, 91, 21))
        self.ChannelOrganoidLabel = QLabel(self.OrganoidSegmentationPage)
        self.ChannelOrganoidLabel.setObjectName(u"ChannelOrganoidLabel")
        self.ChannelOrganoidLabel.setGeometry(QRect(10, 40, 49, 22))
        self.ChannelOrganoidComboBox = QComboBox(self.OrganoidSegmentationPage)
        self.ChannelOrganoidComboBox.setObjectName(u"ChannelOrganoidComboBox")
        self.ChannelOrganoidComboBox.setGeometry(QRect(70, 40, 259, 22))
        self.Parameter1OrganoidSlider = QSlider(self.OrganoidSegmentationPage)
        self.Parameter1OrganoidSlider.setObjectName(u"Parameter1OrganoidSlider")
        self.Parameter1OrganoidSlider.setGeometry(QRect(100, 112, 201, 21))
        self.Parameter1OrganoidSlider.setMinimum(1)
        self.Parameter1OrganoidSlider.setMaximum(100)
        self.Parameter1OrganoidSlider.setPageStep(10)
        self.Parameter1OrganoidSlider.setValue(45)
        self.Parameter1OrganoidSlider.setOrientation(Qt.Horizontal)
        self.Parameter1OrganoidValueLabel = QLabel(self.OrganoidSegmentationPage)
        self.Parameter1OrganoidValueLabel.setObjectName(u"Parameter1OrganoidValueLabel")
        self.Parameter1OrganoidValueLabel.setGeometry(QRect(310, 110, 21, 21))
        self.KeepLargestOrganoidRadioButton = QRadioButton(self.OrganoidSegmentationPage)
        self.KeepLargestOrganoidRadioButton.setObjectName(u"KeepLargestOrganoidRadioButton")
        self.KeepLargestOrganoidRadioButton.setGeometry(QRect(10, 150, 151, 20))
        self.KeepLargestOrganoidRadioButton.setChecked(True)
        self.KeepMultipleOragnoidRadioButton = QRadioButton(self.OrganoidSegmentationPage)
        self.KeepMultipleOragnoidRadioButton.setObjectName(u"KeepMultipleOragnoidRadioButton")
        self.KeepMultipleOragnoidRadioButton.setGeometry(QRect(10, 190, 171, 20))
        self.VolumeMinOrganoidLineEdit = QLineEdit(self.OrganoidSegmentationPage)
        self.VolumeMinOrganoidLineEdit.setObjectName(u"VolumeMinOrganoidLineEdit")
        self.VolumeMinOrganoidLineEdit.setGeometry(QRect(190, 190, 81, 21))
        self.umOrganoidLabel = QLabel(self.OrganoidSegmentationPage)
        self.umOrganoidLabel.setObjectName(u"umOrganoidLabel")
        self.umOrganoidLabel.setGeometry(QRect(290, 190, 31, 20))
        icon7 = QIcon()
        icon7.addFile(u":/logos/logos/notOrganoid.png", QSize(), QIcon.Normal, QIcon.Off)
        self.SettingsToolBox.addItem(self.OrganoidSegmentationPage, icon7, u"Organoid Segmentation (no detection)")
        self.CellsSegmentationPage = QWidget()
        self.CellsSegmentationPage.setObjectName(u"CellsSegmentationPage")
        self.CellsSegmentationPage.setGeometry(QRect(0, 0, 331, 311))
        self.DetectCellsCheckBox = QCheckBox(self.CellsSegmentationPage)
        self.DetectCellsCheckBox.setObjectName(u"DetectCellsCheckBox")
        self.DetectCellsCheckBox.setGeometry(QRect(10, 10, 121, 20))
        self.DetectCellsCheckBox.setChecked(False)
        self.ChannelCellsLabel = QLabel(self.CellsSegmentationPage)
        self.ChannelCellsLabel.setObjectName(u"ChannelCellsLabel")
        self.ChannelCellsLabel.setGeometry(QRect(10, 40, 49, 22))
        self.ChannelCellsComboBox = QComboBox(self.CellsSegmentationPage)
        self.ChannelCellsComboBox.setObjectName(u"ChannelCellsComboBox")
        self.ChannelCellsComboBox.setGeometry(QRect(70, 40, 259, 22))
        self.RadiusLabel = QLabel(self.CellsSegmentationPage)
        self.RadiusLabel.setObjectName(u"RadiusLabel")
        self.RadiusLabel.setEnabled(False)
        self.RadiusLabel.setGeometry(QRect(180, 110, 81, 21))
        self.MethodCellsComboBox = QComboBox(self.CellsSegmentationPage)
        self.MethodCellsComboBox.addItem("")
        self.MethodCellsComboBox.addItem("")
        self.MethodCellsComboBox.setObjectName(u"MethodCellsComboBox")
        self.MethodCellsComboBox.setGeometry(QRect(70, 74, 259, 22))
        self.MethodCellsLabel = QLabel(self.CellsSegmentationPage)
        self.MethodCellsLabel.setObjectName(u"MethodCellsLabel")
        self.MethodCellsLabel.setGeometry(QRect(10, 74, 49, 22))
        self.RadiusLineEdit = QLineEdit(self.CellsSegmentationPage)
        self.RadiusLineEdit.setObjectName(u"RadiusLineEdit")
        self.RadiusLineEdit.setEnabled(False)
        self.RadiusLineEdit.setGeometry(QRect(259, 110, 70, 21))
        self.RadiusLineEdit.setInputMethodHints(Qt.ImhDigitsOnly)
        self.DistMaxLineEdit = QLineEdit(self.CellsSegmentationPage)
        self.DistMaxLineEdit.setObjectName(u"DistMaxLineEdit")
        self.DistMaxLineEdit.setEnabled(True)
        self.DistMaxLineEdit.setGeometry(QRect(100, 110, 70, 21))
        self.DistMaxLineEdit.setInputMethodHints(Qt.ImhDigitsOnly)
        self.DistMaxLabel = QLabel(self.CellsSegmentationPage)
        self.DistMaxLabel.setObjectName(u"DistMaxLabel")
        self.DistMaxLabel.setEnabled(True)
        self.DistMaxLabel.setGeometry(QRect(10, 110, 91, 21))
        self.cellStainsRadioButton = QRadioButton(self.CellsSegmentationPage)
        self.cellStainsRadioButton.setObjectName(u"cellStainsRadioButton")
        self.cellStainsRadioButton.setGeometry(QRect(10, 150, 181, 20))
        self.cellStainsRadioButton.setChecked(True)
        self.cytoStainsRadioButton = QRadioButton(self.CellsSegmentationPage)
        self.cytoStainsRadioButton.setObjectName(u"cytoStainsRadioButton")
        self.cytoStainsRadioButton.setGeometry(QRect(200, 150, 121, 20))
        icon8 = QIcon()
        icon8.addFile(u":/logos/logos/notCells.png", QSize(), QIcon.Normal, QIcon.Off)
        self.SettingsToolBox.addItem(self.CellsSegmentationPage, icon8, u"Cells Segmentation (no detection)")
        self.InfoButton = QPushButton(self.LeftSideWidget)
        self.InfoButton.setObjectName(u"InfoButton")
        self.InfoButton.setGeometry(QRect(296, 730, 41, 41))
        icon9 = QIcon()
        icon9.addFile(u":/logos/logos/info.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.InfoButton.setIcon(icon9)
        self.InfoButton.setIconSize(QSize(20, 20))
        self.ProcessFileButton = QPushButton(self.LeftSideWidget)
        self.ProcessFileButton.setObjectName(u"ProcessFileButton")
        self.ProcessFileButton.setGeometry(QRect(5, 730, 141, 41))
        icon10 = QIcon()
        icon10.addFile(u":/logos/logos/image.png", QSize(), QIcon.Normal, QIcon.Off)
        self.ProcessFileButton.setIcon(icon10)
        self.BrowseParametersButton = QPushButton(self.LeftSideWidget)
        self.BrowseParametersButton.setObjectName(u"BrowseParametersButton")
        self.BrowseParametersButton.setGeometry(QRect(256, 730, 41, 41))
        icon11 = QIcon()
        icon11.addFile(u"logos/roue.png", QSize(), QIcon.Normal, QIcon.Off)
        self.BrowseParametersButton.setIcon(icon11)
        self.BrowseParametersButton.setIconSize(QSize(20, 20))

        self.verticalLayout_2.addWidget(self.LeftSideWidget)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout_2.addItem(self.verticalSpacer)


        self.horizontalLayout_2.addLayout(self.verticalLayout_2)

        self.RightSideTabWidget = QTabWidget(self.centralwidget)
        self.RightSideTabWidget.setObjectName(u"RightSideTabWidget")
        self.RightSideTabWidget.setMinimumSize(QSize(711, 738))
        font = QFont()
        font.setKerning(True)
        self.RightSideTabWidget.setFont(font)
        self.RightSideTabWidget.setAutoFillBackground(False)
        self.RightSideTabWidget.setStyleSheet(u"")
        self.RightSideTabWidget.setTabShape(QTabWidget.Rounded)
        self.RightSideTabWidget.setElideMode(Qt.ElideNone)
        self.ImageVisualisationTab = QWidget()
        self.ImageVisualisationTab.setObjectName(u"ImageVisualisationTab")
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.ImageVisualisationTab.sizePolicy().hasHeightForWidth())
        self.ImageVisualisationTab.setSizePolicy(sizePolicy1)
        self.ImageVisualisationTab.setMinimumSize(QSize(705, 709))
        self.verticalLayout = QVBoxLayout(self.ImageVisualisationTab)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.ImageFrame = QFrame(self.ImageVisualisationTab)
        self.ImageFrame.setObjectName(u"ImageFrame")
        sizePolicy2 = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.ImageFrame.sizePolicy().hasHeightForWidth())
        self.ImageFrame.setSizePolicy(sizePolicy2)
        self.ImageFrame.setMinimumSize(QSize(500, 600))
        self.ImageFrame.setFrameShape(QFrame.StyledPanel)
        self.ImageFrame.setFrameShadow(QFrame.Raised)

        self.verticalLayout.addWidget(self.ImageFrame)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.ZValueLabel = QLabel(self.ImageVisualisationTab)
        self.ZValueLabel.setObjectName(u"ZValueLabel")
        self.ZValueLabel.setMaximumSize(QSize(20, 20))

        self.horizontalLayout_3.addWidget(self.ZValueLabel)

        self.ImageViewerSlider = QSlider(self.ImageVisualisationTab)
        self.ImageViewerSlider.setObjectName(u"ImageViewerSlider")
        sizePolicy3 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.ImageViewerSlider.sizePolicy().hasHeightForWidth())
        self.ImageViewerSlider.setSizePolicy(sizePolicy3)
        self.ImageViewerSlider.setOrientation(Qt.Horizontal)

        self.horizontalLayout_3.addWidget(self.ImageViewerSlider)

        self.changeViewCheckBox = QCheckBox(self.ImageVisualisationTab)
        self.changeViewCheckBox.setObjectName(u"changeViewCheckBox")

        self.horizontalLayout_3.addWidget(self.changeViewCheckBox)


        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.ChannelVisualisationLabel = QLabel(self.ImageVisualisationTab)
        self.ChannelVisualisationLabel.setObjectName(u"ChannelVisualisationLabel")
        sizePolicy4 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.ChannelVisualisationLabel.sizePolicy().hasHeightForWidth())
        self.ChannelVisualisationLabel.setSizePolicy(sizePolicy4)

        self.horizontalLayout.addWidget(self.ChannelVisualisationLabel)

        self.ChannelVisualisationComboBox = QComboBox(self.ImageVisualisationTab)
        self.ChannelVisualisationComboBox.setObjectName(u"ChannelVisualisationComboBox")
        self.ChannelVisualisationComboBox.setEnabled(False)

        self.horizontalLayout.addWidget(self.ChannelVisualisationComboBox)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_2)

        self.PreprocessingCheckBox = QCheckBox(self.ImageVisualisationTab)
        self.PreprocessingCheckBox.setObjectName(u"PreprocessingCheckBox")
        self.PreprocessingCheckBox.setEnabled(False)

        self.horizontalLayout.addWidget(self.PreprocessingCheckBox)

        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_3)

        self.MaskVisualisationLabel = QLabel(self.ImageVisualisationTab)
        self.MaskVisualisationLabel.setObjectName(u"MaskVisualisationLabel")
        sizePolicy4.setHeightForWidth(self.MaskVisualisationLabel.sizePolicy().hasHeightForWidth())
        self.MaskVisualisationLabel.setSizePolicy(sizePolicy4)

        self.horizontalLayout.addWidget(self.MaskVisualisationLabel)

        self.MaskVisualisationComboBox = QComboBox(self.ImageVisualisationTab)
        self.MaskVisualisationComboBox.setObjectName(u"MaskVisualisationComboBox")
        self.MaskVisualisationComboBox.setEnabled(False)

        self.horizontalLayout.addWidget(self.MaskVisualisationComboBox)

        self.horizontalSpacer_4 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_4)

        self.View3DPushButton = QPushButton(self.ImageVisualisationTab)
        self.View3DPushButton.setObjectName(u"View3DPushButton")
        icon12 = QIcon()
        icon12.addFile(u"logos/3D.png", QSize(), QIcon.Normal, QIcon.Off)
        self.View3DPushButton.setIcon(icon12)

        self.horizontalLayout.addWidget(self.View3DPushButton)

        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(6, 1)

        self.verticalLayout.addLayout(self.horizontalLayout)

        icon13 = QIcon()
        icon13.addFile(u":/logos/logos/layers.png", QSize(), QIcon.Normal, QIcon.Off)
        self.RightSideTabWidget.addTab(self.ImageVisualisationTab, icon13, "")
        self.StatisticsTableTab = QWidget()
        self.StatisticsTableTab.setObjectName(u"StatisticsTableTab")
        self.verticalLayout_3 = QVBoxLayout(self.StatisticsTableTab)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.StatisticsTableWidget = QTableWidget(self.StatisticsTableTab)
        if (self.StatisticsTableWidget.columnCount() < 57):
            self.StatisticsTableWidget.setColumnCount(57)
        if (self.StatisticsTableWidget.rowCount() < 25):
            self.StatisticsTableWidget.setRowCount(25)
        self.StatisticsTableWidget.setObjectName(u"StatisticsTableWidget")
        self.StatisticsTableWidget.setRowCount(25)
        self.StatisticsTableWidget.setColumnCount(57)

        self.verticalLayout_3.addWidget(self.StatisticsTableWidget)

        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_4.addItem(self.horizontalSpacer)

        self.TableComboBox = QComboBox(self.StatisticsTableTab)
        self.TableComboBox.setObjectName(u"TableComboBox")

        self.horizontalLayout_4.addWidget(self.TableComboBox)

        self.horizontalSpacer_5 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_4.addItem(self.horizontalSpacer_5)

        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 2)
        self.horizontalLayout_4.setStretch(2, 1)

        self.verticalLayout_3.addLayout(self.horizontalLayout_4)

        icon14 = QIcon()
        icon14.addFile(u":/logos/logos/table.png", QSize(), QIcon.Normal, QIcon.Off)
        self.RightSideTabWidget.addTab(self.StatisticsTableTab, icon14, "")
        self.StatisticsPlotTab = QWidget()
        self.StatisticsPlotTab.setObjectName(u"StatisticsPlotTab")
        self.verticalLayout_4 = QVBoxLayout(self.StatisticsPlotTab)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.PlotFrame = QFrame(self.StatisticsPlotTab)
        self.PlotFrame.setObjectName(u"PlotFrame")
        self.PlotFrame.setFrameShape(QFrame.StyledPanel)
        self.PlotFrame.setFrameShadow(QFrame.Raised)

        self.verticalLayout_4.addWidget(self.PlotFrame)

        self.horizontalLayout_6 = QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.horizontalLayout_6.setContentsMargins(0, 0, -1, -1)
        self.horizontalSpacer_6 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_6.addItem(self.horizontalSpacer_6)

        self.FeaturePlotComboBox = QComboBox(self.StatisticsPlotTab)
        self.FeaturePlotComboBox.addItem("")
        self.FeaturePlotComboBox.addItem("")
        self.FeaturePlotComboBox.addItem("")
        self.FeaturePlotComboBox.addItem("")
        self.FeaturePlotComboBox.addItem("")
        self.FeaturePlotComboBox.addItem("")
        self.FeaturePlotComboBox.addItem("")
        self.FeaturePlotComboBox.addItem("")
        self.FeaturePlotComboBox.addItem("")
        self.FeaturePlotComboBox.addItem("")
        self.FeaturePlotComboBox.addItem("")
        self.FeaturePlotComboBox.addItem("")
        self.FeaturePlotComboBox.addItem("")
        self.FeaturePlotComboBox.addItem("")
        self.FeaturePlotComboBox.addItem("")
        self.FeaturePlotComboBox.addItem("")
        self.FeaturePlotComboBox.addItem("")
        self.FeaturePlotComboBox.addItem("")
        self.FeaturePlotComboBox.addItem("")
        self.FeaturePlotComboBox.addItem("")
        self.FeaturePlotComboBox.addItem("")
        self.FeaturePlotComboBox.addItem("")
        self.FeaturePlotComboBox.setObjectName(u"FeaturePlotComboBox")

        self.horizontalLayout_6.addWidget(self.FeaturePlotComboBox)

        self.horizontalSpacer_7 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_6.addItem(self.horizontalSpacer_7)

        self.PlotTypeComboBox = QComboBox(self.StatisticsPlotTab)
        self.PlotTypeComboBox.addItem("")
        self.PlotTypeComboBox.addItem("")
        self.PlotTypeComboBox.setObjectName(u"PlotTypeComboBox")

        self.horizontalLayout_6.addWidget(self.PlotTypeComboBox)

        self.horizontalSpacer_8 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_6.addItem(self.horizontalSpacer_8)

        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 3)
        self.horizontalLayout_6.setStretch(2, 1)
        self.horizontalLayout_6.setStretch(3, 3)
        self.horizontalLayout_6.setStretch(4, 1)

        self.verticalLayout_4.addLayout(self.horizontalLayout_6)

        icon15 = QIcon()
        icon15.addFile(u":/logos/logos/plot.png", QSize(), QIcon.Normal, QIcon.Off)
        self.RightSideTabWidget.addTab(self.StatisticsPlotTab, icon15, "")

        self.horizontalLayout_2.addWidget(self.RightSideTabWidget)

        OrganoSegmenterWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(OrganoSegmenterWindow)
        self.ImageViewerSlider.valueChanged.connect(self.ZValueLabel.setNum)

        self.FileManagementToolBox.setCurrentIndex(0)
        self.ExportToolBox.setCurrentIndex(0)
        self.SettingsToolBox.setCurrentIndex(0)
        self.RightSideTabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(OrganoSegmenterWindow)
    # setupUi

    def retranslateUi(self, OrganoSegmenterWindow):
        self.BrowseFolderButton.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Browse", None))
        self.ImageFolderLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Images Folder", None))
        self.DeltaXLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"\u0394x", None))
        self.DeltaZLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"\u0394z", None))
        self.DeltaYLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"\u0394y", None))
        self.DeltaYLineEdit.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"1", None))
        self.DeltaXLineEdit.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"1", None))
        self.VoxelSizeLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Voxel Sizes (\u03bcm)", None))
        self.DeltaZLineEdit.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"1", None))
        self.FileManagementToolBox.setItemText(self.FileManagementToolBox.indexOf(self.FileManagementPage), QCoreApplication.translate("OrganoSegmenterWindow", u"File Management", None))
        self.ExportMasksCheckBox.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Masks", None))
        self.ExportOverlaysCheckBox.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Overlays", None))
        self.ExportCompositeCheckBox.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Composite", None))
        self.ExportCSVCheckBox.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"CSV", None))
        self.ExportChannelsCheckBox.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Channels", None))
        self.ExportParametersCheckBox.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Parameters", None))
        self.ExportToolBox.setItemText(self.ExportToolBox.indexOf(self.ExportPage), QCoreApplication.translate("OrganoSegmenterWindow", u"Export", None))
        self.AddPreprocessingButton.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Add", None))
        self.RemovePreprocessingButton.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Remove", None))
        self.ChannelPreprocessingLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Channel", None))
        self.MethodPreprocessingComboBox.setItemText(0, QCoreApplication.translate("OrganoSegmenterWindow", u"correct bleaching", None))
        self.MethodPreprocessingComboBox.setItemText(1, QCoreApplication.translate("OrganoSegmenterWindow", u"gaussian difference", None))
        self.MethodPreprocessingComboBox.setItemText(2, QCoreApplication.translate("OrganoSegmenterWindow", u"gaussian division", None))
        self.MethodPreprocessingComboBox.setItemText(3, QCoreApplication.translate("OrganoSegmenterWindow", u"unsharp mask", None))

        self.PreprocessingMethodLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Method", None))
        self.Parameter1PreprocessingLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Sigma", None))
        self.Parameter1PreprocessingLineEdit.setText("")
        self.Parameter2PreprocessingLineEdit.setText("")
        self.Parameter2PreprocessingLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Amount", None))
        self.SettingsToolBox.setItemText(self.SettingsToolBox.indexOf(self.ChannelsPreprocessingPage), QCoreApplication.translate("OrganoSegmenterWindow", u"Channels Preprocessing", None))
        self.NmsThresholdLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"NMS Threshold", None))
        self.ProbThresholdLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Prob Threshold", None))
        self.ChannelNucleiLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Channel ", None))
        self.VolumeLimitLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Volumes : ", None))
        self.VolumeMaxLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Max", None))
        self.ExploreVolumesWindowButton.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Explore min max volumes", None))
        self.ChangeModelButton.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Load Model", None))
        self.DetectNucleiCheckBox.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Detect Nuclei", None))
        self.ResampleByGroupBox.setTitle(QCoreApplication.translate("OrganoSegmenterWindow", u"Resample by", None))
        self.ResampleXLineEdit.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"0.5", None))
        self.ResampleZLineEdit.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"1", None))
        self.ResampleYLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Y", None))
        self.ResampleYLineEdit.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"0.5", None))
        self.ResampleXLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"X", None))
        self.ResampleZLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Z", None))
        self.AutoResizeWindowButton.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Auto Resize Window", None))
        self.UnityMuLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"(\u03bcm3)", None))
        self.VolumeMinLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Min", None))
        self.NmsValueLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"0.3", None))
        self.ProbValueLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"0.3", None))
        self.DefaultModelComboBox.setItemText(0, QCoreApplication.translate("OrganoSegmenterWindow", u"Default Model", None))
        self.DefaultModelComboBox.setItemText(1, QCoreApplication.translate("OrganoSegmenterWindow", u"Big Nuclei", None))
        self.DefaultModelComboBox.setItemText(2, QCoreApplication.translate("OrganoSegmenterWindow", u"Default 2D Model", None))

        self.SettingsToolBox.setItemText(self.SettingsToolBox.indexOf(self.NucleiSegmentationPage), QCoreApplication.translate("OrganoSegmenterWindow", u"Nuclei Segmentation", None))
        self.DetectOrganoidCheckBox.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Detect Organoid", None))
        self.MethodOrganoidComboBox.setItemText(0, QCoreApplication.translate("OrganoSegmenterWindow", u"Otsu Threshold", None))
        self.MethodOrganoidComboBox.setItemText(1, QCoreApplication.translate("OrganoSegmenterWindow", u"Dynamic Range Threshold", None))

        self.MethodOrganoidLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Method", None))
        self.Parameter1OrganoidLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Otsu Scale ", None))
        self.ChannelOrganoidLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Channel ", None))
        self.Parameter1OrganoidValueLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"0.8", None))
        self.KeepLargestOrganoidRadioButton.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Keep Largest Organoid", None))
        self.KeepMultipleOragnoidRadioButton.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Keep Organoids Larger Than ", None))
        self.VolumeMinOrganoidLineEdit.setText("")
        self.umOrganoidLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"\u03bcm3", None))
        self.SettingsToolBox.setItemText(self.SettingsToolBox.indexOf(self.OrganoidSegmentationPage), QCoreApplication.translate("OrganoSegmenterWindow", u"Organoid Segmentation (no detection)", None))
        self.DetectCellsCheckBox.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Detect Cells", None))
        self.ChannelCellsLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Channel ", None))
        self.RadiusLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Radius (\u00b5m)", None))
        self.MethodCellsComboBox.setItemText(0, QCoreApplication.translate("OrganoSegmenterWindow", u"Watershed intensity channel", None))
        self.MethodCellsComboBox.setItemText(1, QCoreApplication.translate("OrganoSegmenterWindow", u"Watershed distance map", None))

        self.MethodCellsLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Method", None))
        self.RadiusLineEdit.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"5", None))
        self.DistMaxLineEdit.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"14", None))
        self.DistMaxLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Dist max (\u00b5m)", None))
        self.cellStainsRadioButton.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Cytoplasmic membrane stain", None))
        self.cytoStainsRadioButton.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Cytoplasmic stain", None))
        self.SettingsToolBox.setItemText(self.SettingsToolBox.indexOf(self.CellsSegmentationPage), QCoreApplication.translate("OrganoSegmenterWindow", u"Cells Segmentation (no detection)", None))
        self.InfoButton.setText("")
        self.ProcessFileButton.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Test Selected Image", None))
        self.BrowseParametersButton.setText("")
        self.ZValueLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"0", None))
        self.changeViewCheckBox.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"3D View", None))
        self.ChannelVisualisationLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Channel ", None))
        self.PreprocessingCheckBox.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Preprocessing", None))
        self.MaskVisualisationLabel.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"Mask", None))
        self.View3DPushButton.setText(QCoreApplication.translate("OrganoSegmenterWindow", u"3D Parameters", None))
        self.RightSideTabWidget.setTabText(self.RightSideTabWidget.indexOf(self.ImageVisualisationTab), QCoreApplication.translate("OrganoSegmenterWindow", u"Image Visualisation", None))
        self.RightSideTabWidget.setTabText(self.RightSideTabWidget.indexOf(self.StatisticsTableTab), QCoreApplication.translate("OrganoSegmenterWindow", u"Statistics Table", None))
        self.FeaturePlotComboBox.setItemText(0, QCoreApplication.translate("OrganoSegmenterWindow", u"volume_um3", None))
        self.FeaturePlotComboBox.setItemText(1, QCoreApplication.translate("OrganoSegmenterWindow", u"bb_X", None))
        self.FeaturePlotComboBox.setItemText(2, QCoreApplication.translate("OrganoSegmenterWindow", u"bb_Y", None))
        self.FeaturePlotComboBox.setItemText(3, QCoreApplication.translate("OrganoSegmenterWindow", u"bb_Z", None))
        self.FeaturePlotComboBox.setItemText(4, QCoreApplication.translate("OrganoSegmenterWindow", u"bb_W", None))
        self.FeaturePlotComboBox.setItemText(5, QCoreApplication.translate("OrganoSegmenterWindow", u"bb_H", None))
        self.FeaturePlotComboBox.setItemText(6, QCoreApplication.translate("OrganoSegmenterWindow", u"bb_WZ", None))
        self.FeaturePlotComboBox.setItemText(7, QCoreApplication.translate("OrganoSegmenterWindow", u"volume", None))
        self.FeaturePlotComboBox.setItemText(8, QCoreApplication.translate("OrganoSegmenterWindow", u"elongation", None))
        self.FeaturePlotComboBox.setItemText(9, QCoreApplication.translate("OrganoSegmenterWindow", u"roundness", None))
        self.FeaturePlotComboBox.setItemText(10, QCoreApplication.translate("OrganoSegmenterWindow", u"equivalent_ellipsoid_diameter_X", None))
        self.FeaturePlotComboBox.setItemText(11, QCoreApplication.translate("OrganoSegmenterWindow", u"equivalent_ellipsoid_diameter_Y", None))
        self.FeaturePlotComboBox.setItemText(12, QCoreApplication.translate("OrganoSegmenterWindow", u"equivalent_ellipsoid_diameter_Z", None))
        self.FeaturePlotComboBox.setItemText(13, QCoreApplication.translate("OrganoSegmenterWindow", u"bb_X_um", None))
        self.FeaturePlotComboBox.setItemText(14, QCoreApplication.translate("OrganoSegmenterWindow", u"bb_Y_um", None))
        self.FeaturePlotComboBox.setItemText(15, QCoreApplication.translate("OrganoSegmenterWindow", u"bb_Z_um", None))
        self.FeaturePlotComboBox.setItemText(16, QCoreApplication.translate("OrganoSegmenterWindow", u"bb_W_um", None))
        self.FeaturePlotComboBox.setItemText(17, QCoreApplication.translate("OrganoSegmenterWindow", u"bb_H_um", None))
        self.FeaturePlotComboBox.setItemText(18, QCoreApplication.translate("OrganoSegmenterWindow", u"bb_WZ_um", None))
        self.FeaturePlotComboBox.setItemText(19, QCoreApplication.translate("OrganoSegmenterWindow", u"equivalent_ellipsoid_diameter_X_um", None))
        self.FeaturePlotComboBox.setItemText(20, QCoreApplication.translate("OrganoSegmenterWindow", u"equivalent_ellipsoid_diameter_Y_um", None))
        self.FeaturePlotComboBox.setItemText(21, QCoreApplication.translate("OrganoSegmenterWindow", u"equivalent_ellipsoid_diameter_Z_um", None))

        self.PlotTypeComboBox.setItemText(0, QCoreApplication.translate("OrganoSegmenterWindow", u"Density repartition", None))
        self.PlotTypeComboBox.setItemText(1, QCoreApplication.translate("OrganoSegmenterWindow", u"Boxplot", None))

        self.PlotTypeComboBox.setCurrentText(QCoreApplication.translate("OrganoSegmenterWindow", u"Density repartition", None))
        self.RightSideTabWidget.setTabText(self.RightSideTabWidget.indexOf(self.StatisticsPlotTab), QCoreApplication.translate("OrganoSegmenterWindow", u"Statistics Plot", None))
        pass
    # retranslateUi


